---
disableExternalSecrets: false
waitForMetalNode: false

vmDefaults:
  accessMode: "ReadWriteMany"
  storageClassName: "ocs-storagecluster-ceph-rbd-virtualization"
  volumeMode: "Block"
  count: 1
  flavor: medium
  workload: server
  os: rhel9
  storage: 30Gi
  memory: 4Gi
  machineType: pc-q35-rhel8.4.0
  cores: 1
  sockets: 1
  threads: 1
  template: rhel9-server-medium
  sshsecret: secret/data/global/vm-ssh
  cloudinitsecret: secret/data/global/cloud-init
  sshpubkeyfield: publickey
  publishService: true
  serviceType: LoadBalancer
  extraLabels:
    drprotection: true
  # extraLabels is available for default extra labels to add to the virtualmachine
  # extraAnnotations is available for default extra labels to add to the virtualmachine
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22

vms:
  edgenode:
    count: 4
    role: node
