apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    app.kubernetes.io/name: placement-binding-hub
    app.kubernetes.io/component: placement-binding
  name: binding-openshift-plus-hub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
placementRef:
  name: placement-openshift-plus-hub
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-ocm-observability
  kind: Policy
  apiGroup: policy.open-cluster-management.io
- name: policy-observability-storage
  kind: Policy
  apiGroup: policy.open-cluster-management.io
