---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  annotations:
    cluster.open-cluster-management.io/experimental-scheduling-disable: "true"
    drplacementcontrol.ramendr.openshift.io/drpc-name: gitops-vm-protection
    drplacementcontrol.ramendr.openshift.io/drpc-namespace: openshift-dr-ops
    argocd.argoproj.io/sync-wave: "8"
  name: gitops-vm-protection-placement-1
  namespace: openshift-dr-ops
spec:
  decisionStrategy:
    groupStrategy:
      clustersPerDecisionGroup: 0
  prioritizerPolicy:
    mode: Additive
  spreadPolicy: {}
