apiVersion: batch/v1
kind: Job
metadata:
  name: submariner-sg-tagger
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: submariner-sg-tag
    app.kubernetes.io/component: aws-tagging
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: sg-tagger
        image: quay.io/validatedpatterns/utility-contaiiner:latest
        command:
        - /bin/bash
        - -c
        - |
{{ .Files.Get "scripts/submariner-sg-tag.sh" | indent 10 }}
        env:
        - name: AWS_SDK_LOAD_CONFIG
          value: "false"
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
      serviceAccountName: submariner-sg-tagger

