{{- range .Values.regionalDR }}
{{ $clusterSet := .name }}
{{ $clusters := .clusters }}
---
apiVersion: multicluster.odf.openshift.io/v1alpha1
kind: MirrorPeer
metadata:
  labels:
    cluster.open-cluster-management.io/backup: resource
  name: mirrorpeer-{{ $clusterSet }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  items:
  - clusterName: {{ $clusters.primary.name }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  - clusterName: {{ $clusters.secondary.name }}
    storageClusterRef:
      name: ocs-storagecluster
      namespace: openshift-storage
  manageS3: true
  type: async
{{- end }}
